### PR TITLE
Adds options for arguments and parameters

### PR DESCRIPTION
**Pull request by bernhardw**
Helps with minification and theoretical speed improvements.

For some other advantages, see http://toddmotto.com/what-function-window-document-undefined-iife-really-means/

### CODE REVIEW

**Comment by mariusschulz** [comment]
Thank you for your pull request! I'll take a look at it as soon as possible.

**Comment by mariusschulz** [comment]
Sorry that it took a while, but I was quite busy last week.

I like the idea and think that there are a variety of use cases where this capability might come in handy. However, I'm not so sure I like the API, yet. I don't think `params` and `args` should be separate arrays; not every developer knows about the different notion of a function's parameters and a function call's arguments. Also, having to match up the order doesn't feel quite right, in my opinion.

We could do something like this instead:

```js
{
    params: {
        $: jQuery,
        window: window,
        document: document,
        undefined: undefined
    }
}
```

With ECMAScript 2015's property value shorthand syntax, the object literal can be simplified further to optimize for the (common?) case where argument and parameter name are identical:


```js
{
    params: {
        $: jQuery,
        window,
        document,
        undefined
    }
}
```

What do you think?

**Comment by mariusschulz** [comment]
I've given some more thought to your proposal and I must say it has been growing on me. :) Besides, the syntax I outlined above doesn't quite work as intended because the values that are assigned to the properties aren't generally strings (but the global window object, etc.).

I had to add the code myself (see https://github.com/mariusschulz/gulp-iife/commit/85b53d484c23cdd29fa102437b620067de0d22f3) because I've rewritten the code base in ES2015 using TDD. Hat tips, though, and thank you again!

**Comment by bernhardw** [comment]
Thanks a lot for the rewrite, looks great! :+1:
Let me know if you need any additional help.

**Pull request closed without merging**
